#!/bin/env python

"""
Wrapper around srun for running python scripts.
"""
import argparse
import json
import os
import subprocess
import time

if __name__ == "__main__":
    SCRIPT_DIR = os.path.dirname(__file__)
    VENV_LOC = os.path.join(
        'mujoco_playground', '.venv', 'bin', 'activate'
    )
    PARTITION_FILE = os.path.join(SCRIPT_DIR, 'partitions.json')

    parser = argparse.ArgumentParser(
        prog='pace_python',
        description='Launch python using SLURM with the preconfigured virtualenv and GPUs.',
        usage='%(prog)s [options] [args]',
        epilog='Additional arguments are interpreted as either arguments to `python`, or `bash` (if --no-python is passed).'
    )
    parser.add_argument('--clean-logs', action='store_true', help='Set to remove logfiles in this directory before running. Does not submit a job if no extra args passed.')
    parser.add_argument('--job-name', '-J', default='pace_python', help='Name of the slurm job.')
    parser.add_argument('--nodefile', '-F', help='File containing list of eligible nodes to run on. Automatically created as `nodes_<gpu>.txt` if left blank.')
    parser.add_argument('--cpus', default=2, type=int, help='Number of CPU cores desired.')
    parser.add_argument('--mem', default='32G', help='Amount of (CPU) memory desired. Use suffix K|M|G|T')
    parser.add_argument('--gpus', '-G', default='a100', help='GPU to request for the job.')
    parser.add_argument('--gpus-per-node', default=1, type=int, help='Number of GPUs to request')
    parser.add_argument('--no-gpu', action='store_true', help="Don't use a GPU for this job.")
    parser.add_argument('--partition', default=None, help="Override the partition to run on")
    parser.add_argument('--time', default='60', help='Amount of time (in minutes) to allocate for this job.')
    parser.add_argument('--no-python', action='store_true', help="Don't launch python. Still useful if you want the virtualenv, or have your own ex. shell script you want to run in this environment. Extra arguments are interpreted as bash arguments.")
    parser.add_argument('--tunnel-port', default=None, help="Tunnel a port to the node running the python process.")
    parser.add_argument('--env-file', default="pace/default_env.sh", help='File to source environment variables from')

    args, rest = parser.parse_known_args()

    if not os.path.exists(VENV_LOC):
        print(f"Could not find VENV at relative path: {VENV_LOC}")
        print("This script must be run from repository toplevel")
        exit(1)

    if not os.path.exists(PARTITION_FILE):
        print("Could not find partitions definition file.")
        print(f"Generate one by running: bash -c 'cd {SCRIPT_DIR}/slurm_utils; python extract_nodes.py'")
        exit(1)

    with open(PARTITION_FILE, 'r') as partition_file:
        partition_info = json.load(partition_file)

    nodefile = args.nodefile
    if args.nodefile is None:
        nodefile = os.path.join(SCRIPT_DIR, f'nodes_{args.gpus.split(":")[0]}.txt')

    if args.clean_logs:
        os.system('rm -f sbatch_python.log')
        os.system('rm -f sbatch_python.log.*')
        if len(rest) == 0:
            exit(0)

    base_filename = 'sbatch_python.log'
    if os.path.exists(base_filename):
        i = 1
        output_filename = f'{base_filename}.{i}'
        while os.path.exists(output_filename):
            i += 1
            output_filename = f'{base_filename}.{i}'
    else:
        output_filename = base_filename

    script_temp_file = os.path.join(SCRIPT_DIR, '.pace_python.sh')

    with open(script_temp_file, 'w') as script_file:
        if args.no_python:
            exec_line = '$@'
        else:
            exec_line = 'python $@'

        script_file.write(
            f'#!/bin/env bash\n'
            f'echo "Running on nodes: $SLURM_NODELIST"\n'
			f'module load cuda/12.9.1\n'
            f'source {VENV_LOC}\n'
            f'source {args.env_file}\n'
            f'{exec_line}\n'
        )

    cmd_args = [
        '-J', args.job_name,
        '-t', args.time,
        '-c', str(args.cpus),
        '-N', '1',
        '--mem', args.mem,
        '-o', output_filename,
    ]
    if not args.no_gpu:
        if args.partition is not None:
            partition = args.partition
        else:
            partition = partition_info[args.gpus.split(':')[0]]
        cmd_args += [
            '-G', args.gpus,
            '-F', nodefile,
            #'--gpus-per-node', str(args.gpus_per_node),
            '--partition', partition
        ]
    elif args.partition is not None:
        cmd_args += [ '--partition', args.partition ]
    res = subprocess.run(['sbatch'] + cmd_args + [script_temp_file] + rest, capture_output=True, text=True)

    if res.returncode != 0:
        print("sbatch failed!")
        print("stdout:", res.stdout)
        print("stderr:", res.stderr)
        exit(res.returncode)

    # Submitted batch job <jobid>
    job_id = res.stdout.strip().split()[-1]
    print(f"Job ID: {job_id}")

    try:
        extra_procs = []

        if not os.path.exists(output_filename):
            print("Waiting for output file...", end='', flush=True)
            while True:
                if os.path.exists(output_filename):
                    success = False
                    with open(output_filename, 'r') as file:
                        lines_read = 0
                        for line in file:
                            if line.startswith("Running on nodes:"):
                                node_name = line.split(':', 1)[1].strip()
                                success = True
                                break
                            lines_read += 1
                            if lines_read > 20: # It should appear on exactly the 10th line
                                break
                    if success:
                        break
                print(".", end='', flush=True)
                time.sleep(1)
            print()

        if args.tunnel_port is not None:
            ssh_logfile = open(f'{output_filename}.ssh', 'w')
            extra_procs.append(subprocess.Popen(['ssh', '-vvv', '-oStrictHostKeyChecking=no', '-NT', '-L', f'{args.tunnel_port}:127.0.0.1:{args.tunnel_port}', node_name], stdout=ssh_logfile, stderr=ssh_logfile))
        subprocess.run(['tail', '-f', '-n100', output_filename])
    except KeyboardInterrupt:
        subprocess.run(['scancel', job_id])
        for proc in extra_procs:
            proc.terminate()
