#!/usr/bin/env python3

import os
import pathlib
import shutil

SYNC_ROOT = os.environ['SYNC_ROOT']

def is_dir_empty(path):
    if not os.path.exists(path):
        return True
    for _ in os.scandir(path):
        return False
    return True

# Vendored copytree to not try to change permissions...
def _copytree(entries, src, dst, symlinks, ignore, copy_function,
              ignore_dangling_symlinks, dirs_exist_ok=False):
    if ignore is not None:
        ignored_names = ignore(os.fspath(src), [x.name for x in entries])
    else:
        ignored_names = ()

    os.makedirs(dst, exist_ok=dirs_exist_ok)
    errors = []

    for srcentry in entries:
        if srcentry.name in ignored_names:
            continue
        srcname = os.path.join(src, srcentry.name)
        dstname = os.path.join(dst, srcentry.name)
        srcobj = srcentry
        try:
            is_symlink = srcentry.is_symlink()
            if is_symlink and os.name == 'nt':
                # Special check for directory junctions, which appear as
                # symlinks but we want to recurse.
                lstat = srcentry.stat(follow_symlinks=False)
                if lstat.st_reparse_tag == stat.IO_REPARSE_TAG_MOUNT_POINT:
                    is_symlink = False
            if is_symlink:
                linkto = os.readlink(srcname)
                if symlinks:
                    # We can't just leave it to `copy_function` because legacy
                    # code with a custom `copy_function` may rely on copytree
                    # doing the right thing.
                    os.symlink(linkto, dstname)
                    copystat(srcobj, dstname, follow_symlinks=not symlinks)
                else:
                    # ignore dangling symlink if the flag is on
                    if not os.path.exists(linkto) and ignore_dangling_symlinks:
                        continue
                    # otherwise let the copy occur. copy2 will raise an error
                    if srcentry.is_dir():
                        copytree(srcobj, dstname, symlinks, ignore,
                                 copy_function, ignore_dangling_symlinks,
                                 dirs_exist_ok)
                    else:
                        copy_function(srcobj, dstname)
            elif srcentry.is_dir():
                copytree(srcobj, dstname, symlinks, ignore, copy_function,
                         ignore_dangling_symlinks, dirs_exist_ok)
            else:
                # Will raise a SpecialFileError for unsupported file types
                copy_function(srcobj, dstname)
        # catch the Error from the recursive copytree so that we can
        # continue with other files
        except shutil.Error as err:
            errors.extend(err.args[0])
        except OSError as why:
            errors.append((srcname, dstname, str(why)))

    if errors:
        raise shutil.Error(errors)
    return dst

def copytree(src, dst, symlinks=False, ignore=None, copy_function=shutil.copyfile,
             ignore_dangling_symlinks=False, dirs_exist_ok=False):
    """Recursively copy a directory tree and return the destination directory.

    If exception(s) occur, an Error is raised with a list of reasons.

    If the optional symlinks flag is true, symbolic links in the
    source tree result in symbolic links in the destination tree; if
    it is false, the contents of the files pointed to by symbolic
    links are copied. If the file pointed to by the symlink doesn't
    exist, an exception will be added in the list of errors raised in
    an Error exception at the end of the copy process.

    You can set the optional ignore_dangling_symlinks flag to true if you
    want to silence this exception. Notice that this has no effect on
    platforms that don't support os.symlink.

    The optional ignore argument is a callable. If given, it
    is called with the `src` parameter, which is the directory
    being visited by copytree(), and `names` which is the list of
    `src` contents, as returned by os.listdir():

        callable(src, names) -> ignored_names

    Since copytree() is called recursively, the callable will be
    called once for each directory that is copied. It returns a
    list of names relative to the `src` directory that should
    not be copied.

    The optional copy_function argument is a callable that will be used
    to copy each file. It will be called with the source path and the
    destination path as arguments. By default, copy2() is used, but any
    function that supports the same signature (like copy()) can be used.

    If dirs_exist_ok is false (the default) and `dst` already exists, a
    `FileExistsError` is raised. If `dirs_exist_ok` is true, the copying
    operation will continue if it encounters existing directories, and files
    within the `dst` tree will be overwritten by corresponding files from the
    `src` tree.
    """
    with os.scandir(src) as itr:
        entries = list(itr)
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                     ignore=ignore, copy_function=copy_function,
                     ignore_dangling_symlinks=ignore_dangling_symlinks,
                     dirs_exist_ok=dirs_exist_ok)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('target', nargs='?', default='.', help="Directory or file to synchronize. (defaults to current running directory)")
    args = parser.parse_args()

    cur_path = pathlib.Path(os.path.abspath(args.target))
    mod_path = pathlib.Path(SYNC_ROOT)/ os.path.join(*cur_path.parts[3:])
    print(cur_path)
    print(mod_path)

    # Handle local path being nonexistent
    if not os.path.exists(cur_path):
        print("Creating local link")
        # Link to an existing directory or file.
        if os.path.exists(mod_path):
            if os.path.isdir(mod_path):
                ftype = 'directory'
            else:
                ftype = 'file'
            os.symlink(mod_path, cur_path, target_is_directory=(ftype == 'directory'))
            print(f"Linked [new] {cur_path} to [{ftype}] {mod_path}")
            exit(0)

        # Create a pair of directories.
        print("WARNING: Neither path exists. Both paths will be created as directories.")
        res = input("Are you sure about this? [Y/N] ").strip().lower()
        if res == 'n':
            print("Exiting")
            exit(1)

        os.makedirs(mod_path, exist_ok=True)
        os.makedirs(cur_path.parent, exist_ok=True)

        os.symlink(mod_path, cur_path, target_is_directory=True)
        print(f"linked [directory] {cur_path} to [directory] {mod_path}")
        exit(0)

    # Handle if local path is directory
    elif os.path.isdir(cur_path):
        print("Linking local directory")
        if os.path.exists(mod_path) and not os.path.isdir(mod_path):
            print("ERROR: Tried to link a directory (local) to a non directory file (storage)")
            exit(1)
        # Path doesn't exist, or is a directory. Either is OK
        if is_dir_empty(cur_path):
            # Always safe to proceed.
            if os.path.exists(mod_path):
                ftype = 'directory'
            else:
                os.makedirs(mod_path)
                ftype = 'new'
            os.rmdir(cur_path)
            # target_is_directory is ignored except on windows, but whatever
            os.symlink(mod_path, cur_path, target_is_directory=True)
            print(f"Linked [directory] {cur_path} to [{ftype}] {mod_path}")
            exit(0)
        elif is_dir_empty(mod_path):
            # Current is non empty but modified is empty.
            print("WARNING: Current directory is nonempty but target path is empty.")
            print("Files will be moved to storage and directory linked.")
            res = input("Are you sure about this? [Y/N] ").strip().lower()
            if res == 'n':
                print("Exiting")
                exit(1)

            # Make target dir and copy files
            if os.path.exists(mod_path):
                ftype = 'directory'
            else:
                os.makedirs(mod_path.parent, exist_ok=True)
                ftype = 'new'

            # Use copy instead of copy2 to avoid crash due to metadata copy failures
            copytree(cur_path, mod_path, copy_function=shutil.copyfile, dirs_exist_ok=True)

            shutil.rmtree(cur_path)
            os.symlink(mod_path, cur_path, target_is_directory=True)
            print(f"Linked [directory] {cur_path} to [{ftype}] {mod_path}")
            exit(0)

        # Neither directory is empty. Error
        print("ERROR: Both local and storage directories are non empty.")
        exit(1)

    ## Handle local path being a file
    print("Linking local file")
    # Fail if we try to link to an existing path
    if os.path.exists(mod_path):
        print("ERROR: Tried to link a file (local) to an already existent file (storage)")
        print("Resolve this conflict yourself!")
        exit(1)

    os.makedirs(mod_path.parent, exist_ok=True)
    # Use copy instead of copy2 to avoid crash due to metadata copy failures
    shutil.copy(cur_path, mod_path)

    os.remove(cur_path)
    os.symlink(mod_path, cur_path, target_is_directory=True)
    print(f"Linked [file] {cur_path} to [new] {mod_path}")
