"""
VLA Verification Framework: Scene-Graph-Based Verification for Vision-Language-Action Models.

This package implements a first-layer verification pipeline for reasoning VLA models
(e.g., pi0.5). It uses scene graphs as symbolic world models to verify whether
textual subtasks generated by the VLA are feasible given the current scene state.

Architecture (inspired by SayPlan and ConceptGraphs):
  1. Scene Graph Construction: VLM analyzes the scene image to build a structured
     scene graph with nodes (objects, surfaces, fixtures, agent) and edges (spatial
     relationships).
  2. Subtask Translation: An LLM translates natural language subtasks into formal
     DSL actions grounded in the scene graph.
  3. Verification: DSL actions are verified against the scene graph state via
     precondition checking. Accepted actions produce a new scene graph state
     (postcondition / effect).

Key design principles:
  - First-layer verification is purely language-based (no visual input after
    initial scene graph construction) to reduce hallucinations.
  - Scene graph actions are state transitions with preconditions and effects,
    following SayPlan's scene graph simulator approach.
  - The DSL is graph-executable: each action directly maps to scene graph
    operations.
"""

from .scene_graph import SceneGraph, SceneNode, SceneEdge
from .dsl import DSLAction, VerificationResult, verify_and_apply
from .verifier import VLAVerifier, SubtaskVerificationResult
from .subtask_translator import translate_subtask

__all__ = [
    "SceneGraph",
    "SceneNode",
    "SceneEdge",
    "DSLAction",
    "VerificationResult",
    "verify_and_apply",
    "VLAVerifier",
    "SubtaskVerificationResult",
    "translate_subtask",
]
