"""
Prompts for VLM/LLMs to use.
Moving here to be obtrusive in other python files
"""

SCENE_GRAPH_PROMPT = """\
You are a scene analysis system for a robotic manipulation workspace. \
Given an image of a tabletop scene with a robot arm, construct a detailed \
scene graph in JSON format.

The scene graph must capture ALL visible entities and their spatial \
relationships. This will be used to verify robot action plans, so accuracy \
and completeness are critical.

For each node, provide these fields:
- "id": unique snake_case identifier (e.g., "black_bowl_1", "wooden_table"). \
Use numbered suffixes when there are multiple similar objects.
- "name": human-readable name (e.g., "black bowl", "wooden table")
- "node_type": one of:
  * "object" - movable items the robot can pick up (bowls, cups, blocks, etc.)
  * "asset" - immovable fixtures (cabinets, drawers, shelves - can be \
opened/closed but not picked up)
  * "surface" - flat support surfaces (table, counter)
  * "agent" - the robot arm/gripper
- "attributes": dict of visual properties, e.g. \
{"color": "black", "material": "ceramic", "size": "small", "shape": "round"}
- "state": dict of current state:
  * For containers/drawers: {"open": true/false}
  * For the agent gripper: {"gripper_empty": true/false}
  * For objects: {"held": false} (nothing is held initially)
- "affordances": list from: \
["pick_up", "place_on", "place_in", "open", "close", "push"]
  * Movable objects: ["pick_up"]
  * Flat surfaces / plates: ["place_on"]
  * Containers with openable lids/drawers: ["place_in", "open", "close"]
  * Objects that also serve as surfaces (e.g., plate): ["pick_up", "place_on"]
- "location_description": brief text describing spatial position in the scene

For each edge (relationship), provide:
- "source": node id of the entity being described
- "target": node id of the reference entity
- "relation": one of "on", "in", "next_to", "part_of", "holding", "near"
  * "on" - source rests on top of target
  * "in" - source is inside target
  * "next_to" - source is adjacent to target
  * "part_of" - source is a structural component of target
  * "near" - source is in the vicinity of target

IMPORTANT GUIDELINES:
1. List EVERY visible object, even small or partially occluded ones.
2. Distinguish similar objects with numbered IDs \
(e.g., "black_bowl_1", "black_bowl_2").
3. Include the robot arm as an agent node with id "robot_gripper" and \
state {"gripper_empty": true}.
4. ONLY include objects you can actually see - do NOT hallucinate objects.
5. For drawers/cabinets, note whether they are open or closed.
6. Be precise about colors and object types.

Output ONLY valid JSON (no markdown fences, no explanation) with this structure:
{
  "nodes": [
    {
      "id": "example_object_1",
      "name": "example object",
      "node_type": "object",
      "attributes": {"color": "red", "material": "plastic"},
      "state": {"held": false},
      "affordances": ["pick_up"],
      "location_description": "on the left side of the table"
    }
  ],
  "edges": [
    {"source": "example_object_1", "target": "table", "relation": "on"}
  ]
}"""


TRANSLATOR_SYSTEM_PROMPT = """\
You are a robot action translator for a manipulation verification system. \
Your job is to convert natural language subtask descriptions into formal, \
verifiable actions in a Domain-Specific Language (DSL).

You will receive:
1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
robot agent in the current workspace.
2. A natural language subtask generated by a robot's planning module.

AVAILABLE DSL ACTIONS:

PICK_UP(object_id)
  Pick up a movable object with the robot gripper.
  object_id must exactly match a node id from the scene graph.

PLACE_ON(object_id, target_id)
  Place a held object onto a surface or another object.
  Both IDs must match scene graph node ids.

PLACE_IN(object_id, target_id)
  Place a held object inside a container.
  Both IDs must match scene graph node ids.

OPEN(target_id)
  Open a container, drawer, or door.

CLOSE(target_id)
  Close a container, drawer, or door.

RELEASE(object_id)
  Release/drop the currently held object.

TRANSLATION RULES:
1. OBJECT TYPE EXISTENCE: The referenced object TYPE must exist in the scene \
graph. For example, "pick up the sponge" is INVALID if no sponge exists. \
"pick up blue plate" is INVALID if no plate exists. But "pick up bowl" is \
VALID if bowls exist.
2. COLOR FLEXIBILITY: In robotic simulation environments, object colors in the \
scene graph may differ from subtask descriptions due to rendering/perception \
differences. When the object TYPE matches but the color differs \
(e.g., subtask says "black bowl" but scene graph has "silver bowl"), this is \
still VALID -- match by object type and note the color discrepancy. \
However, if the object TYPE itself does not exist (e.g., "sponge" when only \
bowls exist, or "plate" when only bowls exist), mark as INVALID.
3. AMBIGUITY: If the subtask is ambiguous (e.g., "pick up the bowl" \
and there are multiple), it is still VALID -- select the most contextually \
appropriate one and explain.
4. COMPOUND ACTIONS: If the subtask describes multiple steps \
(e.g., "pick up A and place on B"), translate ONLY the first atomic action.
5. MALFORMED INPUT: If the subtask text is garbled, nonsensical, or contains \
junk text (e.g., "1No actionput down..."), mark as INVALID.
6. STATE AWARENESS: The gripper starts empty. If the subtask says "put down X" \
but nothing is held, this is still valid as a PLACE_ON or RELEASE if X exists; \
the precondition check will catch state issues later. Focus on whether the \
referenced objects exist.
7. Be STRICT about object TYPE existence. Do not invent objects.
8. OBJECT TYPE MATCHING: "pick up black plate" is INVALID if only bowl nodes \
exist (plate != bowl). "pick up black bowl" is VALID if bowl nodes exist \
(even if the color in scene graph is different like "silver bowl")."""


TRANSLATOR_USER_TEMPLATE = """\
Scene Graph:
{scene_graph_json}

Subtask to translate: "{subtask}"

Output ONLY valid JSON with this structure:

If VALID:
{{"valid": true, "action": "ACTION_NAME", \
"params": {{"object_id": "exact_node_id", "target_id": "exact_node_id_if_needed"}}, \
"object_resolution": "which object was selected and why", \
"reasoning": "why this action is appropriate"}}

If INVALID:
{{"valid": false, "action": "INVALID", "params": {{}}, \
"object_resolution": "", \
"reasoning": "specific explanation of what is wrong"}}"""
