"""
Translate natural language subtasks (from VLA) into scene graph DSL actions.

Uses an LLM (text-only, no vision) to parse the subtask, ground it in the
scene graph, and produce a structured DSL action for verification.

The translation LLM receives:
  1. The current scene graph (JSON) for context and object resolution.
  2. The natural language subtask from the VLA model.

It outputs a DSL action or marks the subtask as INVALID with reasoning.
"""

import json
import re
from typing import Optional

from .openrouter_client import query_llm, DEFAULT_LLM_MODEL
from .scene_graph import SceneGraph
from .dsl import DSLAction


TRANSLATOR_SYSTEM_PROMPT = """\
You are a robot action translator for a manipulation verification system. \
Your job is to convert natural language subtask descriptions into formal, \
verifiable actions in a Domain-Specific Language (DSL).

You will receive:
1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
robot agent in the current workspace.
2. A natural language subtask generated by a robot's planning module.

AVAILABLE DSL ACTIONS:

PICK_UP(object_id)
  Pick up a movable object with the robot gripper.
  object_id must exactly match a node id from the scene graph.

PLACE_ON(object_id, target_id)
  Place a held object onto a surface or another object.
  Both IDs must match scene graph node ids.

PLACE_IN(object_id, target_id)
  Place a held object inside a container.
  Both IDs must match scene graph node ids.

OPEN(target_id)
  Open a container, drawer, or door.

CLOSE(target_id)
  Close a container, drawer, or door.

RELEASE(object_id)
  Release/drop the currently held object.

TRANSLATION RULES:
1. OBJECT TYPE EXISTENCE: The referenced object TYPE must exist in the scene \
graph. For example, "pick up the sponge" is INVALID if no sponge exists. \
"pick up blue plate" is INVALID if no plate exists. But "pick up bowl" is \
VALID if bowls exist.
2. COLOR FLEXIBILITY: In robotic simulation environments, object colors in the \
scene graph may differ from subtask descriptions due to rendering/perception \
differences. When the object TYPE matches but the color differs \
(e.g., subtask says "black bowl" but scene graph has "silver bowl"), this is \
still VALID -- match by object type and note the color discrepancy. \
However, if the object TYPE itself does not exist (e.g., "sponge" when only \
bowls exist, or "plate" when only bowls exist), mark as INVALID.
3. AMBIGUITY: If the subtask is ambiguous (e.g., "pick up the bowl" \
and there are multiple), it is still VALID -- select the most contextually \
appropriate one and explain.
4. COMPOUND ACTIONS: If the subtask describes multiple steps \
(e.g., "pick up A and place on B"), translate ONLY the first atomic action.
5. MALFORMED INPUT: If the subtask text is garbled, nonsensical, or contains \
junk text (e.g., "1No actionput down..."), mark as INVALID.
6. STATE AWARENESS: The gripper starts empty. If the subtask says "put down X" \
but nothing is held, this is still valid as a PLACE_ON or RELEASE if X exists; \
the precondition check will catch state issues later. Focus on whether the \
referenced objects exist.
7. Be STRICT about object TYPE existence. Do not invent objects.
8. OBJECT TYPE MATCHING: "pick up black plate" is INVALID if only bowl nodes \
exist (plate != bowl). "pick up black bowl" is VALID if bowl nodes exist \
(even if the color in scene graph is different like "silver bowl")."""


TRANSLATOR_USER_TEMPLATE = """\
Scene Graph:
{scene_graph_json}

Subtask to translate: "{subtask}"

Output ONLY valid JSON with this structure:

If VALID:
{{"valid": true, "action": "ACTION_NAME", \
"params": {{"object_id": "exact_node_id", "target_id": "exact_node_id_if_needed"}}, \
"object_resolution": "which object was selected and why", \
"reasoning": "why this action is appropriate"}}

If INVALID:
{{"valid": false, "action": "INVALID", "params": {{}}, \
"object_resolution": "", \
"reasoning": "specific explanation of what is wrong"}}"""


def _extract_json(text: str) -> dict:
    """Extract JSON from LLM response (may have markdown fences or thinking)."""
    code_block = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
    if code_block:
        json_str = code_block.group(1).strip()
    else:
        brace_start = text.find("{")
        if brace_start < 0:
            raise json.JSONDecodeError("No JSON found", text, 0)
        depth = 0
        json_end = brace_start
        for i in range(brace_start, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    json_end = i + 1
                    break
        json_str = text[brace_start:json_end]

    return json.loads(json_str)


def translate_subtask(
    subtask: str,
    scene_graph: SceneGraph,
    llm_model: str = DEFAULT_LLM_MODEL,
    api_key: Optional[str] = None,
) -> DSLAction:
    """
    Translate a natural language subtask into a DSL action using an LLM.

    The LLM receives only text (scene graph JSON + subtask string),
    ensuring the first-layer verification is purely language-based.

    Args:
        subtask: Natural language subtask from VLA model.
        scene_graph: Current scene graph state (provides context).
        llm_model: OpenRouter model ID for the translation LLM.
        api_key: OpenRouter API key.

    Returns:
        DSLAction -- the translated action (or INVALID with reasoning).
    """
    sg_json = scene_graph.to_json(indent=2)

    user_prompt = TRANSLATOR_USER_TEMPLATE.format(
        scene_graph_json=sg_json,
        subtask=subtask,
    )

    print(f"  [LLM] Querying {llm_model} for subtask translation...")
    raw_response = query_llm(
        prompt=user_prompt,
        system_prompt=TRANSLATOR_SYSTEM_PROMPT,
        model=llm_model,
        api_key=api_key,
        temperature=0.1,
    )
    print(f"  [LLM] Response received ({len(raw_response)} chars)")

    try:
        result = _extract_json(raw_response)
    except (json.JSONDecodeError, ValueError) as e:
        print(f"  [LLM] WARNING: Failed to parse response: {e}")
        print(f"  [LLM] Raw: {raw_response[:500]}")
        return DSLAction(
            action_type="INVALID",
            reasoning=f"LLM returned unparseable response: {str(e)}",
        )

    if result.get("valid", False):
        return DSLAction(
            action_type=result.get("action", "INVALID"),
            params=result.get("params", {}),
            reasoning=result.get("reasoning", ""),
            object_resolution=result.get("object_resolution", ""),
        )
    else:
        return DSLAction(
            action_type="INVALID",
            params=result.get("params", {}),
            reasoning=result.get("reasoning", "Marked invalid by translator"),
            object_resolution=result.get("object_resolution", ""),
        )
