"""
First-layer verification pipeline for VLA subtask verification using scene graphs.

This module ties together the scene graph, DSL, and LLM translator to provide
a complete verification pipeline for reasoning VLA models like pi0.5.

Pipeline:
  1. Construct a scene graph from an initial scene image (VLM, one-time).
  2. For each generated subtask from the VLA:
     a. Translate subtask -> DSL action (LLM, text-only).
     b. Verify DSL action preconditions against scene graph state.
     c. If accepted: apply effects -> produce successor scene graph.
     d. If rejected: return feedback with reasons.

Design principles:
  - After initial construction, all verification is language-only (no vision).
  - Scene graph acts as a symbolic world model (SayPlan-style).
  - Actions are state transitions with pre/postconditions.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .scene_graph import SceneGraph
from .scene_graph_constructor import construct_scene_graph as _construct_sg
from .subtask_translator import translate_subtask
from .dsl import DSLAction, VerificationResult, verify_and_apply
from .openrouter_client import DEFAULT_VLM_MODEL, DEFAULT_LLM_MODEL


@dataclass
class SubtaskVerificationResult:
    """Complete result of verifying a single subtask."""
    subtask: str
    dsl_action: DSLAction
    verification: VerificationResult
    scene_graph_before: Optional[dict] = None
    scene_graph_after: Optional[dict] = None

    @property
    def accepted(self) -> bool:
        return self.verification.success

    def summary(self) -> str:
        status = "ACCEPTED" if self.accepted else "REJECTED"
        lines = [
            f"Subtask: \"{self.subtask}\"",
            f"Status: {status}",
            f"DSL Action: {self.dsl_action.action_type}({self.dsl_action.params})",
        ]
        if self.dsl_action.object_resolution:
            lines.append(f"Object Resolution: {self.dsl_action.object_resolution}")
        if self.dsl_action.reasoning:
            lines.append(f"Translator Reasoning: {self.dsl_action.reasoning}")
        lines.append(f"Verification: {self.verification.message}")
        if not self.accepted and self.verification.failed_preconditions:
            lines.append(
                f"Failed Preconditions: {self.verification.failed_preconditions}"
            )
        return "\n".join(lines)


class VLAVerifier:
    """
    First-layer verification pipeline for VLA-generated subtasks.

    Uses scene graphs as a symbolic world model to verify whether textual
    subtasks generated by a reasoning VLA (e.g., pi0.5) are feasible.

    Usage:
        verifier = VLAVerifier()
        verifier.construct_scene_graph(image_path)
        result = verifier.verify_subtask("pick up the black bowl")
        print(result.summary())
    """

    def __init__(
        self,
        vlm_model: str = DEFAULT_VLM_MODEL,
        llm_model: str = DEFAULT_LLM_MODEL,
        api_key: Optional[str] = None,
    ):
        self.vlm_model = vlm_model
        self.llm_model = llm_model
        self.api_key = api_key
        self.scene_graph: Optional[SceneGraph] = None

    def construct_scene_graph(self, image_path: Path) -> SceneGraph:
        """Construct the initial scene graph from an image using a VLM."""
        self.scene_graph = _construct_sg(
            image_path=image_path,
            vlm_model=self.vlm_model,
            api_key=self.api_key,
        )
        return self.scene_graph

    def load_scene_graph(self, scene_graph: SceneGraph):
        """Load a pre-constructed scene graph (e.g., from JSON)."""
        self.scene_graph = scene_graph

    def verify_subtask(
        self, subtask: str, update_state: bool = False,
    ) -> SubtaskVerificationResult:
        """
        Verify a single subtask against the current scene graph.

        Args:
            subtask: Natural language subtask from VLA.
            update_state: If True and the subtask is accepted, update the
                internal scene graph to the successor state.

        Returns:
            SubtaskVerificationResult with accept/reject and feedback.
        """
        if self.scene_graph is None:
            raise RuntimeError(
                "Scene graph not initialized. "
                "Call construct_scene_graph() or load_scene_graph() first."
            )

        scene_before = self.scene_graph.to_dict()

        dsl_action = translate_subtask(
            subtask=subtask,
            scene_graph=self.scene_graph,
            llm_model=self.llm_model,
            api_key=self.api_key,
        )

        verification = verify_and_apply(dsl_action, self.scene_graph)

        scene_after = None
        if verification.success and verification.resulting_graph is not None:
            scene_after = verification.resulting_graph.to_dict()
            if update_state:
                self.scene_graph = verification.resulting_graph

        return SubtaskVerificationResult(
            subtask=subtask,
            dsl_action=dsl_action,
            verification=verification,
            scene_graph_before=scene_before,
            scene_graph_after=scene_after,
        )

    def get_scene_graph(self) -> Optional[SceneGraph]:
        """Return the current scene graph."""
        return self.scene_graph

    def reset_scene_graph(self, scene_graph: SceneGraph):
        """Reset the scene graph to a given state."""
        self.scene_graph = scene_graph
