"""
First-layer verification pipeline for VLA subtask verification using scene graphs.

This module ties together the scene graph, DSL, and LLM translator to provide
a complete verification pipeline for reasoning VLA models like pi0.5.

Pipeline:
  1. Construct a scene graph from an initial scene image (VLM, one-time).
  2. For each generated subtask from the VLA:
     a. Translate subtask -> PDDL action (LLM, text-only).
     b. Verify PDDL action preconditions against scene graph state.
     c. If accepted: apply effects -> produce successor scene graph.
     d. If rejected: return feedback with reasons.

Design principles:
  - After initial construction, all verification is language-only (no vision).
  - Scene graph acts as a symbolic world model (SayPlan-style).
  - Actions are state transitions with pre/postconditions.
"""

from dataclasses import dataclass
import json
import textwrap
import time
import copy

import numpy as np

import re
from pddlsim.simulation import Simulation

from llm_apis.llm_tool import extract_json_from_response
from llm_apis import transformers_api

from .scene_graph import TaskSceneGraph

@dataclass
class SubtaskVerificationResult:
    """Complete result of verifying a single subtask."""
    subtask: str
    accepted: bool
    reasoning: str
    grounded_action: str = None

    def summary(self) -> str:
        status = "ACCEPTED" if self.accepted else "REJECTED"
        lines = [
            f"Subtask: \"{self.subtask}\"",
            f"Status: {status}",
            f"Action: {self.grounded_action}",
        ]
        lines.append(f"Translator Reasoning: {self.reasoning}")
        return "\n".join(lines)


class VLAVerifier:
    """
    First-layer verification pipeline for VLA-generated subtasks.

    Uses scene graphs as a symbolic world model to verify whether textual
    subtasks generated by a reasoning VLA (e.g., pi0.5) are feasible.
    """

    def __init__(self, scene_graph: TaskSceneGraph, llm_interface, vlm_interface=None):
        self.scene_graph = scene_graph
        self.skill_plan = None
        self.current_skill = None
        skill_completion_interface = vlm_interface if vlm_interface is not None else llm_interface

        # Dynamically build VLM and LLM requiring functions.
        self.translate_subtask = llm_interface(
            self._translate_subtask,
            system_prompt=VLAVerifier.TRANSLATOR_SYSTEM_PROMPT.format(pddl_domain=scene_graph.pddl_domain_desc)
        )

        self.translate_skill = llm_interface(
            self._translate_skill,
            system_prompt=VLAVerifier.SKILL_TRANSLATOR_SYSTEM_PROMPT.format(pddl_domain=scene_graph.pddl_domain_desc)
        )

        self.verify_skill_completion = skill_completion_interface(
            self._verify_skill_completion,
            system_prompt=VLAVerifier.SKILL_COMPLETION_VERIFIER_SYSTEM_PROMPT.format(pddl_domain=scene_graph.pddl_domain_desc)
        )

    def _translate_subtask(self, llm_response, subtask: str, scene_graph: TaskSceneGraph):
        # TODO: rewrite
        """
        Translate a natural language subtask into a DSL action using an LLM.

        The LLM receives only text (scene graph JSON + subtask string),
        ensuring the first-layer verification is purely language-based.

        Args:
            subtask: Natural language subtask from VLA model.

        Returns:
            SubtaskVerificationResult -- the translated action (or INVALID with reasoning).
        """

        avail_actions = json.dumps(self.scene_graph.get_available_actions(), indent=2)

        user_prompt = VLAVerifier.TRANSLATOR_USER_TEMPLATE.format(
            scene_graph_json=json.dumps(scene_graph.to_dict(include_grounding=False), indent=2),
            subtask=subtask,
            avail_actions=avail_actions
        )
        t0 = time.monotonic()
        print(f"  [LLM] Querying LLM for subtask translation...")
        yield [ transformers_api.make_message(user_prompt) ]

        raw_response = llm_response['content']
        try:
            result = extract_json_from_response(raw_response)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"  [LLM] WARNING: Failed to parse response: {e}")
            print(f"  [LLM] Raw: {raw_response[:500]}")
            yield SubtaskVerificationResult(
                subtask=subtask,
                accepted=False,
                reasoning=f"LLM returned unparseable response: {str(e)}",
                grounded_action="<No action output>"
            )
        t1 = time.monotonic()
        print(f"  [LLM] Time elapsed: {t1 - t0}")

        yield SubtaskVerificationResult(
            subtask=subtask,
            accepted=result['status'].strip().lower() == 'success',
            reasoning=result.get("reason", "<No reasoning output>"),
            grounded_action=result.get("chosen_action", "<No action output>")
        )
    TRANSLATOR_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a robot action translator for a manipulation verification system. \
    Your job is to convert natural language subtask descriptions into formal, \
    verifiable actions in PDDL. The PDDL domain is given below:

    ```pddl
    {pddl_domain}
    ```

    You will receive:
    1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
    robot agent in the current workspace.
    2. A natural language subtask generated by a robot's planning module.
    3. A list of actions the PDDL description describes as allowed.
        These have the following format:
        ```json
        {{
          "name": <action name from pddl>,
          "parameters": <json list of pddl objects this action applies to, in order>
        }}
        ```
        Refer to the PDDL domain for the specifics of each action.

    You should translate the natural language task into the closest \
    approximation of the requested subtask, in PDDL form. Some color difference \
    is allowed -- for example, the user may specify to pick up a pink cube when \
    the scene graph only has red or blue cubes; in this case the red cube should \
    be chosen. You should be lenient with shades of color, \
    (accepting silver as white or grey as black, for example),
    but you should reject translations that have different hues (red vs blue) \
    or large differences in shade (white vs black).

    If the natural language task has errors such as garbled text or other nonsense, \
    you should reject the action.

    You should output a json object of this form:

    ```json
    {{
      "status": "SUCCESS" | "FAILURE"
      "reason": <specific reason for failure or choice of action>
      "chosen_action": <copy of the action to perform>
    }}
    ```

    If the status is FAILURE, you should omit chosen_action.

    """)

    TRANSLATOR_USER_TEMPLATE = textwrap.dedent("""\
    Scene Graph:
    {scene_graph_json}

    Subtask to translate: "{subtask}"

    Available actions:
    ```json
    {avail_actions}
    ```
    """)


    def verify_subtask(self, subtask: str) -> SubtaskVerificationResult:
        """
        Verify a single subtask against the current scene graph.

        Args:
            subtask: Natural language subtask from VLA.
            update_state: If True and the subtask is accepted, update the
                internal scene graph to the successor state.

        Returns:
            SubtaskVerificationResult with accept/reject and feedback.
        """

        return self.translate_subtask(subtask=subtask, scene_graph=self.scene_graph)
    

    def verify_skill(self, skill: str) -> SubtaskVerificationResult:
        """
        Verify a single skill against the current scene graph.

        Args:
            skill: Natural language manipulation skill from VLA.

        Returns:
            SubtaskVerificationResult with accept/reject and feedback.
        """
        return self.translate_skill(skill=skill, scene_graph=self.scene_graph)

    
    def _translate_skill(self, llm_response, skill: str, scene_graph: TaskSceneGraph):
        """
        Translate a natural language reasoning skill to pddl action

        The LLM receives only text (scene graph JSON + subtask string),
        ensuring the first-layer verification is purely language-based.

        Args:
            subtask: Natural language subtask from VLA model.

        Returns:
            SubtaskVerificationResult -- the translated action (or INVALID with reasoning).
        """

        avail_actions = json.dumps(self.scene_graph.get_available_actions(), indent=2)

        user_prompt = VLAVerifier.SKILL_TRANSLATOR_USER_TEMPLATE.format(
            scene_graph_json=json.dumps(scene_graph.to_dict(include_grounding=False), indent=2),
            skill=skill,
            avail_actions=avail_actions
        )
        t0 = time.monotonic()
        print(f"  [LLM] Querying LLM for subtask translation...")
        yield [ transformers_api.make_message(user_prompt) ]

        raw_response = llm_response['content']
        try:
            result = extract_json_from_response(raw_response)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"  [LLM] WARNING: Failed to parse response: {e}")
            print(f"  [LLM] Raw: {raw_response[:500]}")
            yield SubtaskVerificationResult(
                subtask=skill,
                accepted=False,
                reasoning=f"LLM returned unparseable response: {str(e)}",
                grounded_action="<No action output>"
            )
        t1 = time.monotonic()
        print(f"  [LLM] Time elapsed: {t1 - t0}")

        yield SubtaskVerificationResult(
            subtask=skill,
            accepted=result['status'].strip().lower() == 'success',
            reasoning=result.get("reason", "<No reasoning output>"),
            grounded_action=result.get("chosen_action", "<No action output>")
        )
    SKILL_TRANSLATOR_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a robot action translator for a manipulation verification system. \
    Your job is to convert textualrobot manipulation skill descriptions into formal, \
    verifiable actions in PDDL. The PDDL domain is given below:

    ```pddl
    {pddl_domain}
    ```

    You will receive:
    1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
    robot agent in the current workspace.
    2. A natural language manipulation skill generated by a robot's planning module.
    3. A list of actions the PDDL description describes as allowed.
        These have the following format:
        ```json
        {{
          "name": <action name from pddl>,
          "parameters": <json list of pddl objects this action applies to, in order>
        }}
        ```
        Refer to the PDDL domain for the specifics of each action.

    You should translate the natural language manipulation skill into the closest \
    approximation of the actions in PDDL form. The manipulation skills typically follow the following format:

    1) PLACE_ON(object1, object2)
    - description: place object1 onto object2
    - object1: the object being placed
    - object2: object that will support object1
    - likely equivalent PDDL action: place_on

    2) PLACE_IN(object1, object2)
    - description: place object1 into object2
    - object1: the object being placed
    - object2: object that will contain object1
    - likely equivalent PDDL action: place_in

    3) PICKUP_FROM(object1, object2)
    - description: pick up object1 from object2
    - object1: the object being picked up. This must be a movable object that can be picked up.
    - object2: object that supports object1 originally
    - likely equivalent PDDL action: pickup_from

    4) OPEN(object)
    - object: the object being opened
    - likely equivalent PDDL action: open

    5) CLOSE(object)
    - object: the object being closed
    - likely equivalent PDDL action: close

    6) TURN_ON(object)
    - object: the object being turned on
    - likely equivalent PDDL action: turn_on

    7) TURN_OFF(object)
    - object: the object being turned off
    - likely equivalent PDDL action: turn_off
    
    Some color difference in object descriptions is allowed -- for example, the user may specify to pick up a black bowl when \
    the scene graph only has silver bowls; in this case the silver bowl should \
    be chosen. You should be lenient with shades of color, \
    (accepting silver as white or silver as black, for example),
    but you should reject translations that have different hues (red vs blue) \
    or large differences in shade (white vs black).

    If the natural language task has errors such as garbled text or other nonsense, \
    you should reject the action.

    You should output a json object of this form:

    ```json
    {{
      "status": "SUCCESS" | "FAILURE"
      "reason": <specific reason for failure or choice of action>
      "chosen_action": <copy of the action to perform>
    }}
    ```

    If the status is FAILURE, you should omit chosen_action.

    """)

    SKILL_TRANSLATOR_USER_TEMPLATE = textwrap.dedent("""\
    Scene Graph:
    {scene_graph_json}

    skill to translate: "{skill}"

    Available actions:
    ```json
    {avail_actions}
    ```
    """)


    def _format_current_predicate_state(self, scene_graph: TaskSceneGraph):
        predicates = []
        for pred in sorted(scene_graph.simulator.state, key=lambda pred: repr(pred)):
            targets = [obj.value for obj in pred.assignment]
            if targets:
                predicates.append(f"({pred.name.value} {' '.join(targets)})")
            else:
                predicates.append(f"({pred.name.value})")
        return "\n".join(predicates)


    def _verify_skill_completion(self, llm_response, image_rgb, skill: str, scene_graph: TaskSceneGraph):
        """
        Use a VLM to verify whether the observation shows that the claimed skill
        has actually been completed, conditioned on the current symbolic state.
        """
        current_scene_graph_json = json.dumps(
            scene_graph.to_dict(include_grounding=False),
            indent=2,
        )
        current_predicates = self._format_current_predicate_state(scene_graph)

        # print("current_scene_graph_json-----------> ", current_scene_graph_json)
        # print("current_predicates-----------> ", current_predicates)

        user_prompt = VLAVerifier.SKILL_COMPLETION_VERIFIER_USER_TEMPLATE.format(
            scene_graph_json=current_scene_graph_json,
            current_predicates=current_predicates,
            skill=skill,
        )
        t0 = time.monotonic()
        print(f"  [VLM] Querying VLM for skill completion verification...")
        yield [transformers_api.make_message(texts=[user_prompt], images=[image_rgb])]

        raw_response = llm_response['content']
        try:
            result = extract_json_from_response(raw_response)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"  [VLM] WARNING: Failed to parse response: {e}")
            print(f"  [VLM] Raw: {raw_response[:500]}")
            yield SubtaskVerificationResult(
                subtask=skill,
                accepted=False,
                reasoning=f"VLM returned unparseable response: {str(e)}",
                grounded_action=None,
            )
            return
        t1 = time.monotonic()
        print(f"  [VLM] Time elapsed: {t1 - t0}")

        completed_flag = result.get("skill_completed")
        if isinstance(completed_flag, str):
            normalized = completed_flag.strip().lower()
            if normalized in {"true", "completed", "yes"}:
                completed_flag = True
            elif normalized in {"false", "not_completed", "not completed", "no"}:
                completed_flag = False
        if not isinstance(completed_flag, bool):
            completed_flag = False

        yield SubtaskVerificationResult(
            subtask=skill,
            accepted=completed_flag,
            reasoning=result.get("reason", "<No reasoning output>"),
            grounded_action=None,
        )
    SKILL_COMPLETION_VERIFIER_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a multimodal verifier for a robot manipulation system.

    Your job is to decide whether the robot's CURRENT RGB observation really
    shows that a claimed manipulation skill has already been completed.

    The PDDL domain is given below for semantic reference only:

    ```pddl
    {pddl_domain}
    ```

    You will receive:
    1. The current RGB image.
    2. The current symbolic scene graph state as JSON.
    3. The same symbolic state as a list of current predicates taken directly
       from the verifier's latest simulator state after forward simulation.
    4. The manipulation skill that the VLA claims is already completed.

    The skill usually looks like one of:
    - PLACE_IN(object1, object2)
    - PLACE_ON(object1, object2)
    - PICKUP_FROM(object1, object2)
    - OPEN(object)
    - CLOSE(object)
    - TURN_ON(object)
    - TURN_OFF(object)

    Use the scene graph state and the predicates as what should be true if the claimed skill is completed.
    Use the image as the primary source of truth for actual scene observation. 
    Compare the actual scene observation with the scene graph state and predicates to determine if the claimed skill is completed.
    If "left" or "right" is mentioned in the skill, it is with respect to the robot's perspective, which is opposite to the viewer's perspective. 
    The scene graph convention is also with respect to the robot's perspective.

    Return `skill_completed: true` only when the visual evidence clearly shows
    the claimed skill is already complete right now. If the image is ambiguous,
    partially occluded, inconsistent with the scene graph state and predicates, or only weakly
    suggests completion, return `skill_completed: false`.

    You should output a json object of this form:

    ```json
    {{
      "skill_completed": true | false,
      "reason": <brief explanation grounded in the image and, if relevant, the scene graph>,
    }}
    ```
    """)

    SKILL_COMPLETION_VERIFIER_USER_TEMPLATE = textwrap.dedent("""\
    Current scene graph (JSON):
    ```json
    {scene_graph_json}
    ```

    Current symbolic predicates from the verifier's latest simulator state:
    ```lisp
    {current_predicates}
    ```

    Skill the VLA claims is completed: "{skill}"

    Decide whether the current RGB observation actually shows that this skill is
    completed now. Use the symbolic state as a hint, but if the image does not
    clearly support completion, return `"skill_completed": false`.
    """)


    def _parse_plan_steps(self, raw_plan):

        text = raw_plan.strip()
        if not text:
            return []

        numbered_matches = list(re.finditer(r"(?:^|\s)(\d+)\.\s*", text))
        if numbered_matches:
            steps = []
            for i, match in enumerate(numbered_matches):
                start = match.end()
                end = (
                    numbered_matches[i + 1].start()
                    if i + 1 < len(numbered_matches)
                    else len(text)
                )
                step_text = text[start:end].strip(" \n\t;")
                if step_text:
                    steps.append(step_text)
            if steps:
                return steps

        return [
            chunk.strip(" \n\t-")
            for chunk in re.split(r"[\n;]+", text)
            if chunk.strip()
        ]


    def _normalize_grounded_action(self, action_obj: dict):
        """
        Normalize a grounded action produced from LLM
        """
        name = action_obj.get("name")
        params = action_obj.get("parameters", [])
        if not isinstance(name, str) or not isinstance(params, list):
            return None
        if not all(isinstance(x, str) for x in params):
            return None
        return name.strip(), [x.strip() for x in params]


    def verify_skill_plan(self, plan):
        """
        Verify a multi-step plan by translating each step and forward-simulating
        grounded PDDL actions on a temporary simulator.

        Args:
            plan: Either a numbered string plan (e.g., "1. ... 2. ...")

        Returns:
            dict with keys:
                feasible (bool),
                failed_step (int | None),
                failure_reason (str | None),
                steps (list[str]),
                applied_actions (list[str]),
                step_results (list[SubtaskVerificationResult]).
        """
        steps = self._parse_plan_steps(plan)
        if not steps:
            raise ValueError("verify_plan received an empty plan.")

        step_results = []
        applied_actions = []

        copy_scene_graph = copy.deepcopy(self.scene_graph)

        for step_idx, skill in enumerate(steps, start=1):
            print(f"[PLAN] Step {step_idx}/{len(steps)}: {skill}")

            result = self.verify_skill(skill)
            step_results.append(result)

            if not result.accepted:
                reason = result.reasoning
                print(f"[PLAN] FAILED at step {step_idx}: {reason}")
                # self.scene_graph.reset_simulator()
                self.scene_graph = copy_scene_graph
                return {
                    "feasible": False,
                    "failed_step": step_idx,
                    "failure_reason": reason,
                    "steps": steps,
                    "applied_actions": applied_actions,
                    "step_results": step_results,
                }

            action_name, action_params = self._normalize_grounded_action(result.grounded_action)
            matched_action = self.scene_graph.match_grounded_action(
                action_name,
                action_params,
            )
            if matched_action is None:
                reason = (
                    "Translator returned an action that is not available in the "
                    f"current symbolic state: {action_name}({', '.join(action_params)})"
                )
                print(f"[PLAN] FAILED at step {step_idx}: {reason}")
                # self.scene_graph.reset_simulator()
                self.scene_graph = copy_scene_graph
                return {
                    "feasible": False,
                    "failed_step": step_idx,
                    "failure_reason": reason,
                    "steps": steps,
                    "applied_actions": applied_actions,
                    "step_results": step_results,
                }

            self.scene_graph.apply_action(matched_action)

            applied_str = f"{action_name}({', '.join(action_params)})"
            applied_actions.append(applied_str)
            print(f"[PLAN] Applied: {applied_str}")

        print(f"[PLAN] SUCCESS: all {len(steps)} steps are symbolically feasible.")

        # Restore simulator so repeated calls always start from the same baseline.
        # self.scene_graph.reset_simulator()
        self.scene_graph = copy_scene_graph

        return {
            "feasible": True,
            "failed_step": None,
            "failure_reason": None,
            "steps": steps,
            "applied_actions": applied_actions,
            "step_results": step_results,
        }
    
    
    def set_skill_plan(self, plan: str):
        """
        parse a string skill plan into an ordered list of skills to be executed sequentially
        """
        self.skill_plan = self._parse_plan_steps(plan)
        self.current_skill = None

    
    def verify_skill_transition(self, next_skill: str, image_rgb=None):
        """
        ASSUME: the skill plan has already been verified, and thus has to be executed sequentially (no forward/backward jumps)

        verification 1: the next skill must be the next skill in the planned skills list (i.e. sequential execution)
        verification 2: if an image is provided, verify with a VLM that the previously active skill is truly completed
        if both verifications passed, transition verification suceeds, forward simulate scene graph, and pop the skill from the planned skills list
        if either verification fails, verification fails, no change to scene graph or skill plan
        Returns:
            dict with keys:
                feasible (bool),
                failure_reason (str | None),
        """
        # sanity check: no skill plan is set
        if not self.skill_plan:
            return {
                "feasible": False,
                "failure_reason": "No remaining skill plan is set",
            }

        # verification 1: the next skill must be the next skill in the planned skills list
        if next_skill != self.skill_plan[0]:
            return {
                "feasible": False,
                "failure_reason": f"Next skill is not the next skill in the planned skills list: {next_skill} != {self.skill_plan[0]}",
            }
        
        # verification 2: if we have an observation, verify that the previous skill is visually complete before accepting the transition.
        if self.current_skill is not None and image_rgb is not None:
            completion_result = self.verify_skill_completion(
                image_rgb=image_rgb,
                skill=self.current_skill,
                scene_graph=self.scene_graph)

            if not completion_result.accepted:
                return {
                    "feasible": False,
                    "failure_reason": (
                        f"Skill completion check failed for {self.current_skill}: "
                        f"{completion_result.reasoning}"
                    ),
                }
        
        # if both verifications passed, verification suceeds, forward simulate scene graph, and pop the skill from the planned skills list
        result = self.verify_skill(next_skill)  # call verify_skill to get the grounded pddl action
        if not result.accepted:
            reason = result.reasoning
            self.scene_graph.reset_simulator()
            return {
                "feasible": False,
                "failure_reason": reason,
            }

        action_name, action_params = self._normalize_grounded_action(result.grounded_action)
        matched_action = self.scene_graph.match_grounded_action(
            action_name,
            action_params,
        )
        self.scene_graph.apply_action(matched_action)

        self.skill_plan.pop(0)
        self.current_skill = next_skill

        return {
            "feasible": True,
            "failure_reason": None,
        }
