"""
First-layer verification pipeline for VLA subtask verification using scene graphs.

This module ties together the scene graph, DSL, and LLM translator to provide
a complete verification pipeline for reasoning VLA models like pi0.5.

Pipeline:
  1. Construct a scene graph from an initial scene image (VLM, one-time).
  2. For each generated subtask from the VLA:
     a. Translate subtask -> PDDL action (LLM, text-only).
     b. Verify PDDL action preconditions against scene graph state.
     c. If accepted: apply effects -> produce successor scene graph.
     d. If rejected: return feedback with reasons.

Design principles:
  - After initial construction, all verification is language-only (no vision).
  - Scene graph acts as a symbolic world model (SayPlan-style).
  - Actions are state transitions with pre/postconditions.
"""

from dataclasses import dataclass
import json
import textwrap
import time

import numpy as np

import re
from pddlsim.simulation import Simulation

from llm_apis.llm_tool import extract_json_from_response
from llm_apis import transformers_api

from .scene_graph import TaskSceneGraph

@dataclass
class SubtaskVerificationResult:
    """Complete result of verifying a single subtask."""
    subtask: str
    accepted: bool
    reasoning: str
    grounded_action: str = None

    def summary(self) -> str:
        status = "ACCEPTED" if self.accepted else "REJECTED"
        lines = [
            f"Subtask: \"{self.subtask}\"",
            f"Status: {status}",
            f"Action: {self.grounded_action}",
        ]
        lines.append(f"Translator Reasoning: {self.reasoning}")
        return "\n".join(lines)


class VLAVerifier:
    """
    First-layer verification pipeline for VLA-generated subtasks.

    Uses scene graphs as a symbolic world model to verify whether textual
    subtasks generated by a reasoning VLA (e.g., pi0.5) are feasible.
    """

    def __init__(self, scene_graph: TaskSceneGraph, llm_interface):
        self.scene_graph = scene_graph

        # Dynamically build VLM and LLM requiring functions.
        self.translate_subtask = llm_interface(
            self._translate_subtask,
            system_prompt=VLAVerifier.TRANSLATOR_SYSTEM_PROMPT.format(pddl_domain=scene_graph.pddl_domain_desc)
        )

        self.translate_skill = llm_interface(
            self._translate_skill,
            system_prompt=VLAVerifier.SKILL_TRANSLATOR_SYSTEM_PROMPT.format(pddl_domain=scene_graph.pddl_domain_desc)
        )

    def _translate_subtask(self, llm_response, subtask: str, scene_graph: TaskSceneGraph):
        # TODO: rewrite
        """
        Translate a natural language subtask into a DSL action using an LLM.

        The LLM receives only text (scene graph JSON + subtask string),
        ensuring the first-layer verification is purely language-based.

        Args:
            subtask: Natural language subtask from VLA model.

        Returns:
            SubtaskVerificationResult -- the translated action (or INVALID with reasoning).
        """

        avail_actions = json.dumps(self.scene_graph.get_available_actions(), indent=2)

        user_prompt = VLAVerifier.TRANSLATOR_USER_TEMPLATE.format(
            scene_graph_json=json.dumps(scene_graph.to_dict(include_grounding=False), indent=2),
            subtask=subtask,
            avail_actions=avail_actions
        )
        t0 = time.monotonic()
        print(f"  [LLM] Querying LLM for subtask translation...")
        yield [ transformers_api.make_message(user_prompt) ]

        raw_response = llm_response['content']
        try:
            result = extract_json_from_response(raw_response)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"  [LLM] WARNING: Failed to parse response: {e}")
            print(f"  [LLM] Raw: {raw_response[:500]}")
            yield SubtaskVerificationResult(
                subtask=subtask,
                accepted=False,
                reasoning=f"LLM returned unparseable response: {str(e)}",
                grounded_action="<No action output>"
            )
        t1 = time.monotonic()
        print(f"  [LLM] Time elapsed: {t1 - t0}")

        yield SubtaskVerificationResult(
            subtask=subtask,
            accepted=result['status'].strip().lower() == 'success',
            reasoning=result.get("reason", "<No reasoning output>"),
            grounded_action=result.get("chosen_action", "<No action output>")
        )
    TRANSLATOR_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a robot action translator for a manipulation verification system. \
    Your job is to convert natural language subtask descriptions into formal, \
    verifiable actions in PDDL. The PDDL domain is given below:

    ```pddl
    {pddl_domain}
    ```

    You will receive:
    1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
    robot agent in the current workspace.
    2. A natural language subtask generated by a robot's planning module.
    3. A list of actions the PDDL description describes as allowed.
        These have the following format:
        ```json
        {{
          "name": <action name from pddl>,
          "parameters": <json list of pddl objects this action applies to, in order>
        }}
        ```
        Refer to the PDDL domain for the specifics of each action.

    You should translate the natural language task into the closest \
    approximation of the requested subtask, in PDDL form. Some color difference \
    is allowed -- for example, the user may specify to pick up a pink cube when \
    the scene graph only has red or blue cubes; in this case the red cube should \
    be chosen. You should be lenient with shades of color, \
    (accepting silver as white or grey as black, for example),
    but you should reject translations that have different hues (red vs blue) \
    or large differences in shade (white vs black).

    If the natural language task has errors such as garbled text or other nonsense, \
    you should reject the action.

    You should output a json object of this form:

    ```json
    {{
      "status": "SUCCESS" | "FAILURE"
      "reason": <specific reason for failure or choice of action>
      "chosen_action": <copy of the action to perform>
    }}
    ```

    If the status is FAILURE, you should omit chosen_action.

    """)

    TRANSLATOR_USER_TEMPLATE = textwrap.dedent("""\
    Scene Graph:
    {scene_graph_json}

    Subtask to translate: "{subtask}"

    Available actions:
    ```json
    {avail_actions}
    ```
    """)


    def verify_subtask(self, subtask: str) -> SubtaskVerificationResult:
        """
        Verify a single subtask against the current scene graph.

        Args:
            subtask: Natural language subtask from VLA.
            update_state: If True and the subtask is accepted, update the
                internal scene graph to the successor state.

        Returns:
            SubtaskVerificationResult with accept/reject and feedback.
        """

        return self.translate_subtask(subtask=subtask, scene_graph=self.scene_graph)
    

    def verify_skill(self, skill: str) -> SubtaskVerificationResult:
        """
        Verify a single skill against the current scene graph.

        Args:
            skill: Natural language manipulation skill from VLA.

        Returns:
            SubtaskVerificationResult with accept/reject and feedback.
        """
        return self.translate_skill(skill=skill, scene_graph=self.scene_graph)

    
    def _translate_skill(self, llm_response, skill: str, scene_graph: TaskSceneGraph):
        """
        Translate a natural language reasoning skill to pddl action

        The LLM receives only text (scene graph JSON + subtask string),
        ensuring the first-layer verification is purely language-based.

        Args:
            subtask: Natural language subtask from VLA model.

        Returns:
            SubtaskVerificationResult -- the translated action (or INVALID with reasoning).
        """

        avail_actions = json.dumps(self.scene_graph.get_available_actions(), indent=2)

        user_prompt = VLAVerifier.SKILL_TRANSLATOR_USER_TEMPLATE.format(
            scene_graph_json=json.dumps(scene_graph.to_dict(include_grounding=False), indent=2),
            skill=skill,
            avail_actions=avail_actions
        )
        t0 = time.monotonic()
        print(f"  [LLM] Querying LLM for subtask translation...")
        yield [ transformers_api.make_message(user_prompt) ]

        raw_response = llm_response['content']
        try:
            result = extract_json_from_response(raw_response)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"  [LLM] WARNING: Failed to parse response: {e}")
            print(f"  [LLM] Raw: {raw_response[:500]}")
            yield SubtaskVerificationResult(
                subtask=skill,
                accepted=False,
                reasoning=f"LLM returned unparseable response: {str(e)}",
                grounded_action="<No action output>"
            )
        t1 = time.monotonic()
        print(f"  [LLM] Time elapsed: {t1 - t0}")

        yield SubtaskVerificationResult(
            subtask=skill,
            accepted=result['status'].strip().lower() == 'success',
            reasoning=result.get("reason", "<No reasoning output>"),
            grounded_action=result.get("chosen_action", "<No action output>")
        )
    SKILL_TRANSLATOR_SYSTEM_PROMPT = textwrap.dedent("""\
    You are a robot action translator for a manipulation verification system. \
    Your job is to convert textualrobot manipulation skill descriptions into formal, \
    verifiable actions in PDDL. The PDDL domain is given below:

    ```pddl
    {pddl_domain}
    ```

    You will receive:
    1. A scene graph (JSON) describing all objects, surfaces, assets, and the \
    robot agent in the current workspace.
    2. A natural language manipulation skill generated by a robot's planning module.
    3. A list of actions the PDDL description describes as allowed.
        These have the following format:
        ```json
        {{
          "name": <action name from pddl>,
          "parameters": <json list of pddl objects this action applies to, in order>
        }}
        ```
        Refer to the PDDL domain for the specifics of each action.

    You should translate the natural language manipulation skill into the closest \
    approximation of the actions in PDDL form. The manipulation skills typically follow the following format:

    1) PLACE(object1, object2, preposition)
    - object1: the object being placed
    - object2: destination/support object
    - preposition: relative relation (e.g., inside, on top of)
    - likely equivalent PDDL action: place_in or place_on

    2) PICK(object)
    - object: the object being picked
    - likely equivalent PDDL action: pickup_from

    3) OPEN(object)
    - object: the object being opened
    - likely equivalent PDDL action: open

    4) CLOSE(object)
    - object: the object being closed
    - likely equivalent PDDL action: close
        
    
    Some color difference in object descriptions is allowed -- for example, the user may specify to pick up a pink cube when \
    the scene graph only has red or blue cubes; in this case the red cube should \
    be chosen. You should be lenient with shades of color, \
    (accepting silver as white or grey as black, for example),
    but you should reject translations that have different hues (red vs blue) \
    or large differences in shade (white vs black).

    If the natural language task has errors such as garbled text or other nonsense, \
    you should reject the action.

    You should output a json object of this form:

    ```json
    {{
      "status": "SUCCESS" | "FAILURE"
      "reason": <specific reason for failure or choice of action>
      "chosen_action": <copy of the action to perform>
    }}
    ```

    If the status is FAILURE, you should omit chosen_action.

    """)

    SKILL_TRANSLATOR_USER_TEMPLATE = textwrap.dedent("""\
    Scene Graph:
    {scene_graph_json}

    skill to translate: "{skill}"

    Available actions:
    ```json
    {avail_actions}
    ```
    """)


    def _parse_plan_steps(self, raw_plan):

        text = raw_plan.strip()
        if not text:
            return []

        numbered_matches = list(re.finditer(r"(?:^|\s)(\d+)\.\s*", text))
        if numbered_matches:
            steps = []
            for i, match in enumerate(numbered_matches):
                start = match.end()
                end = (
                    numbered_matches[i + 1].start()
                    if i + 1 < len(numbered_matches)
                    else len(text)
                )
                step_text = text[start:end].strip(" \n\t;")
                if step_text:
                    steps.append(step_text)
            if steps:
                return steps

        return [
            chunk.strip(" \n\t-")
            for chunk in re.split(r"[\n;]+", text)
            if chunk.strip()
        ]


    def _normalize_grounded_action(self, action_obj: dict):
        """
        Normalize a grounded action produced from LLM
        """
        name = action_obj.get("name")
        params = action_obj.get("parameters", [])
        if not isinstance(name, str) or not isinstance(params, list):
            return None
        if not all(isinstance(x, str) for x in params):
            return None
        return name.strip(), [x.strip() for x in params]


    def verify_skill_plan(self, plan):
        """
        Verify a multi-step plan by translating each step and forward-simulating
        grounded PDDL actions on a temporary simulator.

        Args:
            plan: Either a numbered string plan (e.g., "1. ... 2. ...")

        Returns:
            dict with keys:
                feasible (bool),
                failed_step (int | None),
                failure_reason (str | None),
                steps (list[str]),
                applied_actions (list[str]),
                step_results (list[SubtaskVerificationResult]).
        """
        steps = self._parse_plan_steps(plan)
        if not steps:
            raise ValueError("verify_plan received an empty plan.")

        step_results = []
        applied_actions = []

        for step_idx, skill in enumerate(steps, start=1):
            print(f"[PLAN] Step {step_idx}/{len(steps)}: {skill}")

            result = self.verify_skill(skill)
            step_results.append(result)

            if not result.accepted:
                reason = result.reasoning
                print(f"[PLAN] FAILED at step {step_idx}: {reason}")
                self.scene_graph.reset_simulator()
                return {
                    "feasible": False,
                    "failed_step": step_idx,
                    "failure_reason": reason,
                    "steps": steps,
                    "applied_actions": applied_actions,
                    "step_results": step_results,
                }

            action_name, action_params = self._normalize_grounded_action(result.grounded_action)
            matched_action = self.scene_graph.match_grounded_action(
                action_name,
                action_params,
            )
            if matched_action is None:
                reason = (
                    "Translator returned an action that is not available in the "
                    f"current symbolic state: {action_name}({', '.join(action_params)})"
                )
                print(f"[PLAN] FAILED at step {step_idx}: {reason}")
                self.scene_graph.reset_simulator()
                return {
                    "feasible": False,
                    "failed_step": step_idx,
                    "failure_reason": reason,
                    "steps": steps,
                    "applied_actions": applied_actions,
                    "step_results": step_results,
                }

            self.scene_graph.apply_action(matched_action)

            applied_str = f"{action_name}({', '.join(action_params)})"
            applied_actions.append(applied_str)
            print(f"[PLAN] Applied: {applied_str}")

        print(f"[PLAN] SUCCESS: all {len(steps)} steps are symbolically feasible.")

        # Restore simulator so repeated calls always start from the same baseline.
        self.scene_graph.reset_simulator()

        return {
            "feasible": True,
            "failed_step": None,
            "failure_reason": None,
            "steps": steps,
            "applied_actions": applied_actions,
            "step_results": step_results,
        }